# Eğitim Paint Uygulaması - Pre-commit Konfigürasyonu
# Bu dosya, Git commit öncesi otomatik kontrolleri tanımlar

repos:
  # Black - Kod formatlayıcı
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py36]

  # isort - Import sıralama
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Flake8 - Lint kontrolü
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # MyPy - Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # Bandit - Güvenlik analizi
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, demo1/]

  # Safety - Güvenlik kontrolü
  - repo: https://github.com/PyUP/safety
    rev: 2.3.5
    hooks:
      - id: safety
        args: [--full-report]

  # Trailing whitespace kontrolü
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
      - id: requirements-txt-fixer

  # Commitizen - Commit mesaj standartları
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Pyupgrade - Python sürüm güncellemeleri
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  # Autoflake - Kullanılmayan import'ları temizle
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variables]

  # Pylint - Detaylı kod analizi
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
      - id: pylint
        args: [--disable=C0114,C0116,C0115]  # Docstring uyarılarını kapat

  # Yapf - Alternatif kod formatlayıcı (Black ile birlikte)
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [--style=google]

  # Codespell - Yazım kontrolü
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: [--ignore-words-list=pyglet,tkinter,pyc,pyo,pyd]

  # Vulture - Ölü kod tespiti
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
        args: [demo1/]

  # Mccabe - Karmaşıklık analizi
  - repo: https://github.com/pycqa/mccabe
    rev: 0.7.0
    hooks:
      - id: mccabe
        args: [--max-complexity=10]

  # Pydocstyle - Docstring stil kontrolü
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]

  # Check-manifest - MANIFEST.in kontrolü
  - repo: https://github.com/mgedmin/check-manifest
    rev: v0.49
    hooks:
      - id: check-manifest

  # Validate-pyproject - pyproject.toml kontrolü
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
      - id: validate-pyproject

# Genel ayarlar
default_language_version:
  python: python3

# Hook ayarları
ci:
  autofix_commit_msg: "ci: pre-commit automatic fixes"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
